Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 128

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Rakefile
